### ISSUE TITLE
Using a mirror service with S3 urls

### ISSUE THREAD

**Issue by leenyburger** [imgproxy/imgproxy.rb#173]
I'm using S3 with a Mirror Service in production (active storage). My `storage.yml` config looks like this: 

```
production:
  service: Mirror
  primary: wasabi
  mirrors:
    - backblaze
 ```

Because of this, even when `IMGPROXY_USE_S3_URLS` is properly set, the `s3` urls are not being created because the `image.service` is `ActiveStorage::Service::MirrorService` not `ActiveStorage::Service::S3Service`.

In `url_adapters/active_storage.rb` the call to `use_s3_url` fails because of the check for `S3` service.
